// Product copy shared by screens, dialogs and design controls.
const khmerProductCopy = <String, String>{
  "1. Add this key to your authenticator app":
      "១. បន្ថែមលេខសម្ងាត់នេះទៅកម្មវិធីផ្ទៀងផ្ទាត់របស់អ្នក",
  "2. Enter the code it shows": "២. បញ្ចូលលេខកូដដែលកម្មវិធីបង្ហាញ",
  "A few lines on what you do and what you are looking for":
      "សរសេរខ្លីៗអំពីការងាររបស់អ្នក និងអ្វីដែលអ្នកកំពុងស្វែងរក",
  "A lowercase letter": "អក្សរតូចមួយ",
  "A number": "លេខមួយ",
  "A symbol": "និមិត្តសញ្ញាមួយ",
  "AI allowance reset. Refresh to see current usage.":
      "ចំនួនប្រើប្រាស់ AI បានកំណត់ឡើងវិញ។ ផ្ទុកឡើងវិញដើម្បីមើលការប្រើប្រាស់បច្ចុប្បន្ន។",
  "AI allowance unavailable. Retry to check usage.":
      "មិនអាចពិនិត្យចំនួនប្រើប្រាស់ AI បាន។ ព្យាយាមម្តងទៀត។",
  "AI analysis could not finish": "មិនអាចបញ្ចប់ការវិភាគ AI បាន",
  "AI bio writer": "ឧបករណ៍សរសេរជីវប្រវត្តិ AI",
  "AI cover letter": "លិខិតអមពាក្យស្នើសុំ AI",
  "AI rewrites your resume content. Review generated details before exporting.":
      "AI កែសម្រួលមាតិកាប្រវត្តិរូបការងារ។ ពិនិត្យព័ត៌មានដែលបានបង្កើតមុននាំចេញ។",
  "AI suggestions can be incomplete. Review them against the role and your own experience.":
      "ការណែនាំ AI អាចមិនពេញលេញ។ ពិនិត្យតាមតួនាទី និងបទពិសោធន៍របស់អ្នក។",
  "About the company": "អំពីក្រុមហ៊ុន",
  "About the role": "អំពីតួនាទី",
  "About you": "អំពីអ្នក",
  "About your company": "អំពីក្រុមហ៊ុនរបស់អ្នក",
  "Accept": "ទទួលយក",
  "Account deletion": "ការលុបគណនី",
  "Achievements (one per line)": "សមិទ្ធផល (មួយក្នុងមួយបន្ទាត់)",
  "Add a career scope": "បន្ថែមវិស័យការងារ",
  "Add a code from an authenticator app to your password.":
      "បន្ថែមលេខកូដពីកម្មវិធីផ្ទៀងផ្ទាត់ទៅពាក្យសម្ងាត់របស់អ្នក។",
  "Add a language": "បន្ថែមភាសា",
  "Add a note if you want to. You can send it without one.":
      "បន្ថែមកំណត់សម្គាល់តាមចិត្ត។ អ្នកក៏អាចផ្ញើដោយគ្មានវាបាន។",
  "Add a private hiring note": "បន្ថែមកំណត់សម្គាល់ជ្រើសរើសឯកជន",
  "Add a skill": "បន្ថែមជំនាញ",
  "Add company photos": "បន្ថែមរូបថតក្រុមហ៊ុន",
  "Add experience": "បន្ថែមបទពិសោធន៍",
  "Add image": "បន្ថែមរូបភាព",
  "Add note": "បន្ថែមកំណត់សម្គាល់",
  "Add photo": "បន្ថែមរូបថត",
  "Add suggested skills": "បន្ថែមជំនាញដែលបានណែនាំ",
  "All companies": "ក្រុមហ៊ុនទាំងអស់",
  "All talent": "បេក្ខជនទាំងអស់",
  "Allow microphone access in device settings to record.":
      "អនុញ្ញាតការប្រើមីក្រូហ្វូនក្នុងការកំណត់ឧបករណ៍ដើម្បីថត។",
  "An uppercase letter": "អក្សរធំមួយ",
  "Analyzing both profiles…": "កំពុងវិភាគប្រវត្តិរូបទាំងពីរ…",
  "Answer": "ចម្លើយ",
  "Anything else we should know (optional)":
      "ព័ត៌មានផ្សេងដែលយើងគួរដឹង (មិនចាំបាច់)",
  "Applicant pipeline": "ដំណើរការបេក្ខជន",
  "Apply design": "អនុវត្តការរចនា",
  "Apply for {0}": "ដាក់ពាក្យសម្រាប់ {0}",
  "Apply reviewed changes": "អនុវត្តការកែប្រែដែលបានពិនិត្យ",
  "Apply selected": "អនុវត្តអ្វីដែលបានជ្រើសរើស",
  "Apply summary": "ប្រើសេចក្តីសង្ខេប",
  "At least 8 characters": "យ៉ាងហោចណាស់ ៨ តួអក្សរ",
  "Attach file": "ភ្ជាប់ឯកសារ",
  "Attach recording": "ភ្ជាប់សំឡេងដែលបានថត",
  "Availability": "ពេលវេលាអាចធ្វើការ",
  "Back to the feed": "ត្រឡប់ទៅទំព័រដើម",
  "Benefits": "អត្ថប្រយោជន៍",
  "Bio draft": "សេចក្តីព្រាងជីវប្រវត្តិ",
  "Block": "ទប់ស្កាត់",
  "Block or report": "ទប់ស្កាត់ ឬរាយការណ៍",
  "Block someone from their profile and they appear here.":
      "ទប់ស្កាត់អ្នកណាម្នាក់ពីប្រវត្តិរូបរបស់ពួកគេ ហើយពួកគេនឹងបង្ហាញនៅទីនេះ។",
  "Block {0}?": "ទប់ស្កាត់ {0}?",
  "Browse privately": "រុករកជាឯកជន",
  "Build your resume": "បង្កើតប្រវត្តិរូបការងាររបស់អ្នក",
  "Cancel account deletion": "បោះបង់ការលុបគណនី",
  "Cancel reply": "បោះបង់ការឆ្លើយតប",
  "Career scopes": "វិស័យការងារ",
  "Categories": "ប្រភេទ",
  "Category": "ប្រភេទ",
  "Changes are not synced yet.": "ការកែប្រែមិនទាន់ធ្វើសមកាលកម្មទេ។",
  "Check your connection and try again.":
      "ពិនិត្យការតភ្ជាប់ ហើយព្យាយាមម្តងទៀត។",
  "Check your email": "ពិនិត្យអ៊ីមែលរបស់អ្នក",
  "Checking AI allowance…": "កំពុងពិនិត្យចំនួនប្រើប្រាស់ AI…",
  "Choose": "ជ្រើសរើស",
  "Choose \"enter a setup key\" in the app and paste it.":
      "ជ្រើសរើស «បញ្ចូលលេខសម្ងាត់រៀបចំ» ក្នុងកម្មវិធី ហើយបិទភ្ជាប់វា។",
  "Choose a new password": "ជ្រើសរើសពាក្យសម្ងាត់ថ្មី",
  "Choose a position": "ជ្រើសរើសមុខតំណែង",
  "Choose from career-scope catalog": "ជ្រើសរើសពីបញ្ជីវិស័យការងារ",
  "Choose up to 5 photos at a time": "ជ្រើសរើសរូបថតរហូតដល់ ៥ ក្នុងមួយលើក",
  "Choose whether your identity appears when you view other profiles.":
      "ជ្រើសរើសថាតើបង្ហាញអត្តសញ្ញាណអ្នកពេលមើលប្រវត្តិរូបផ្សេងឬអត់។",
  "Clear all": "សម្អាតទាំងអស់",
  "Clear all notifications?": "លុបការជូនដំណឹងទាំងអស់?",
  "Codes can take a minute to arrive. Check your spam folder too.":
      "លេខកូដអាចចំណាយពេលមួយនាទីទើបទទួលបាន។ ពិនិត្យថតសារឥតបានការផងដែរ។",
  "Color palette": "ក្ដារពណ៌",
  "Column width": "ទទឹងជួរឈរ",
  "Companies": "ក្រុមហ៊ុន",
  "Companies hiring for what you do": "ក្រុមហ៊ុនជ្រើសរើសតាមជំនាញរបស់អ្នក",
  "Companies who liked you back": "ក្រុមហ៊ុនដែលចូលចិត្តអ្នកវិញ",
  "Companies you saved": "ក្រុមហ៊ុនដែលអ្នកបានរក្សាទុក",
  "Company name": "ឈ្មោះក្រុមហ៊ុន",
  "Company photos": "រូបថតក្រុមហ៊ុន",
  "Company type (optional)": "ប្រភេទក្រុមហ៊ុន (មិនចាំបាច់)",
  "Complete": "បញ្ចប់",
  "Confirm new password": "បញ្ជាក់ពាក្យសម្ងាត់ថ្មី",
  "Confirm password": "បញ្ជាក់ពាក្យសម្ងាត់",
  "Connecting to messages…": "កំពុងតភ្ជាប់ទៅសារ…",
  "Copy key": "ចម្លងលេខសម្ងាត់",
  "Copy meeting link": "ចម្លងតំណចូលសម្ភាសន៍",
  "Corners": "ជ្រុង",
  "Could not export the PDF. Please try again.":
      "មិនអាចនាំចេញ PDF បាន។ សូមព្យាយាមម្តងទៀត។",
  "Could not finish writing. Your draft is unchanged.":
      "មិនអាចសរសេរបញ្ចប់បាន។ សេចក្តីព្រាងរបស់អ្នកនៅដដែល។",
  "Could not generate suggestions. Your draft is unchanged.":
      "មិនអាចបង្កើតការណែនាំបាន។ សេចក្តីព្រាងរបស់អ្នកនៅដដែល។",
  "Cover image": "រូបភាពគម្រប",
  "Cover note": "កំណត់សម្គាល់អមពាក្យស្នើសុំ",
  "Cover-letter draft": "សេចក្តីព្រាងលិខិតអមពាក្យស្នើសុំ",
  "Create a password": "បង្កើតពាក្យសម្ងាត់",
  "Create an account": "បង្កើតគណនី",
  "Create and maintain the roles candidates discover and match against.":
      "បង្កើត និងគ្រប់គ្រងតួនាទីដែលបេក្ខជនស្វែងរក និងផ្គូផ្គង។",
  "Create and save export": "បង្កើត និងរក្សាទុកឯកសារនាំចេញ",
  "Create position": "បង្កើតមុខតំណែង",
  "Create resumes for different roles and save them to your account.":
      "បង្កើតប្រវត្តិរូបការងារសម្រាប់តួនាទីផ្សេងៗ ហើយរក្សាទុកក្នុងគណនីរបស់អ្នក។",
  "Create your account": "បង្កើតគណនីរបស់អ្នក",
  "Create your first role to appear in job search and matching.":
      "បង្កើតតួនាទីដំបូងរបស់អ្នកដើម្បីបង្ហាញក្នុងការស្វែងរក និងការផ្គូផ្គងការងារ។",
  "Creates a JSON file with your profile, applications, interviews, matches, saved items, notifications, support reports, and login history. Exports are limited to once every 24 hours.":
      "បង្កើតឯកសារ JSON ដែលមានប្រវត្តិរូប ពាក្យស្នើសុំ សម្ភាសន៍ ការផ្គូផ្គង ធាតុរក្សាទុក ការជូនដំណឹង របាយការណ៍ជំនួយ និងប្រវត្តិចូលគណនី។ អាចនាំចេញម្តងក្នុងរយៈពេល ២៤ ម៉ោង។",
  "Currency": "រូបិយប័ណ្ណ",
  "Custom accent color": "ពណ៌លម្អផ្ទាល់ខ្លួន",
  "Customize the design, then preview the PDF to see the result.":
      "កែសម្រួលការរចនា រួចមើល PDF ដើម្បីមើលលទ្ធផល។",
  "Data export": "ការនាំចេញទិន្នន័យ",
  "Date of birth": "ថ្ងៃខែឆ្នាំកំណើត",
  "Deadline": "ថ្ងៃផុតកំណត់",
  "Decline": "បដិសេធ",
  "Decoration": "ការលម្អ",
  "Delete note": "លុបកំណត់សម្គាល់",
  "Delete resume?": "លុបប្រវត្តិរូបការងារ?",
  "Delete saved search?": "លុបការស្វែងរកដែលបានរក្សាទុក?",
  "Delete this message?": "លុបសារនេះ?",
  "Delete this position?": "លុបមុខតំណែងនេះ?",
  "Delete your account": "លុបគណនីរបស់អ្នក",
  "Delete {0}": "លុប {0}",
  "Delete “{0}” from your account?": "លុប «{0}» ពីគណនីរបស់អ្នក?",
  "Deletion scheduled": "បានកំណត់ពេលលុប",
  "Deletion starts a 30-day grace period. You can cancel at any time during that period.":
      "ការលុបចាប់ផ្តើមរយៈពេលរង់ចាំ ៣០ ថ្ងៃ។ អ្នកអាចបោះបង់គ្រប់ពេលក្នុងរយៈពេលនេះ។",
  "Describe what went wrong and our team can investigate.":
      "ពិពណ៌នាបញ្ហាដែលបានកើតឡើង ដើម្បីឱ្យក្រុមការងារយើងពិនិត្យ។",
  "Description": "ការពិពណ៌នា",
  "Details": "ព័ត៌មានលម្អិត",
  "Didn't get it? Send a new code": "មិនទទួលបាន? ផ្ញើលេខកូដថ្មី",
  "Discard": "បោះបង់ការកែប្រែ",
  "Discard local changes?": "បោះបង់ការកែប្រែលើឧបករណ៍នេះ?",
  "Documents": "ឯកសារ",
  "Download your data": "ទាញយកទិន្នន័យរបស់អ្នក",
  "Duplicate": "ចម្លង",
  "Each switch saves on its own. Security messages are always sent.":
      "ការប្តូរនីមួយៗរក្សាទុកដោយស្វ័យប្រវត្តិ។ សារសុវត្ថិភាពតែងតែផ្ញើ។",
  "Edit message": "កែសម្រួលសារ",
  "Edit position": "កែសម្រួលមុខតំណែង",
  "Edit profile": "កែសម្រួលប្រវត្តិរូប",
  "Education required": "ការអប់រំដែលតម្រូវ",
  "Education style": "រចនាប័ទ្មការអប់រំ",
  "Email changes require account verification.":
      "ការប្តូរអ៊ីមែលត្រូវការផ្ទៀងផ្ទាត់គណនី។",
  "Email or phone number": "អ៊ីមែល ឬលេខទូរស័ព្ទ",
  "Email updates": "ការជូនដំណឹងតាមអ៊ីមែល",
  "Email verified. Welcome to Apsara Talent.":
      "បានផ្ទៀងផ្ទាត់អ៊ីមែល។ សូមស្វាគមន៍មកកាន់ Apsara Talent។",
  "Email verified. You can log in now.":
      "បានផ្ទៀងផ្ទាត់អ៊ីមែល។ អ្នកអាចចូលគណនីបានឥឡូវនេះ។",
  "Employees": "បុគ្គលិក",
  "Employment type": "ប្រភេទការងារ",
  "End date": "កាលបរិច្ឆេទបញ្ចប់",
  "End this match?": "បញ្ចប់ការផ្គូផ្គងនេះ?",
  "Enter a current code from your authenticator app to confirm.":
      "បញ្ចូលលេខកូដបច្ចុប្បន្នពីកម្មវិធីផ្ទៀងផ្ទាត់របស់អ្នកដើម្បីបញ្ជាក់។",
  "Enter the code": "បញ្ចូលលេខកូដ",
  "Enter the email or phone number on your account and we will send a reset token to it.":
      "បញ្ចូលអ៊ីមែល ឬលេខទូរស័ព្ទក្នុងគណនីរបស់អ្នក ហើយយើងនឹងផ្ញើលេខកូដកំណត់ឡើងវិញ។",
  "Enter the reset token you were sent, then your new password.":
      "បញ្ចូលលេខកូដកំណត់ឡើងវិញដែលបានផ្ញើ រួចបញ្ចូលពាក្យសម្ងាត់ថ្មី។",
  "Every candidate on Apsara Talent you have not liked yet":
      "បេក្ខជនទាំងអស់លើ Apsara Talent ដែលអ្នកមិនទាន់ចុចចូលចិត្ត",
  "Every company on Apsara Talent you have not liked yet":
      "ក្រុមហ៊ុនទាំងអស់លើ Apsara Talent ដែលអ្នកមិនទាន់ចុចចូលចិត្ត",
  "Every notification is deleted for good. What they were about — your matches, applications and interviews — is not affected.":
      "ការជូនដំណឹងទាំងអស់នឹងត្រូវលុបជាអចិន្ត្រៃយ៍។ ការផ្គូផ្គង ពាក្យស្នើសុំ និងសម្ភាសន៍របស់អ្នកមិនរងផលប៉ះពាល់ទេ។",
  "Experience required": "បទពិសោធន៍ដែលតម្រូវ",
  "Experience style": "រចនាប័ទ្មបទពិសោធន៍",
  "Export cover-letter PDF": "នាំចេញលិខិតអមពាក្យស្នើសុំជា PDF",
  "Export interview prep PDF": "នាំចេញការត្រៀមសម្ភាសន៍ជា PDF",
  "Find a role": "ស្វែងរកតួនាទី",
  "Find talent": "ស្វែងរកបេក្ខជន",
  "Finish company setup to manage applicants.":
      "បញ្ចប់ការរៀបចំក្រុមហ៊ុនដើម្បីគ្រប់គ្រងបេក្ខជន។",
  "First name": "នាមខ្លួន",
  "First, tell us which side of the match you are on.":
      "ប្រាប់យើងជាមុនថាអ្នកជាបេក្ខជន ឬក្រុមហ៊ុន។",
  "Founded": "ឆ្នាំបង្កើត",
  "Full-time": "ពេញម៉ោង",
  "Gender": "ភេទ",
  "Generate AI draft": "បង្កើតសេចក្តីព្រាង AI",
  "Generate again": "បង្កើតម្តងទៀត",
  "Generate cover letter": "បង្កើតលិខិតអមពាក្យស្នើសុំ",
  "Generate suggestions": "បង្កើតការណែនាំ",
  "Header layout": "ប្លង់ចំណងជើងខាងលើ",
  "Header style": "រចនាប័ទ្មចំណងជើងខាងលើ",
  "History could not load.": "មិនអាចផ្ទុកប្រវត្តិបាន។",
  "How it works": "របៀបប្រើប្រាស់",
  "How you appear to companies": "របៀបដែលអ្នកបង្ហាញដល់ក្រុមហ៊ុន",
  "Hybrid": "ចម្រុះ",
  "I already have a token": "ខ្ញុំមានលេខកូដរួចហើយ",
  "Import resume": "នាំចូលប្រវត្តិរូបការងារ",
  "Include the steps you took and what you expected to happen.":
      "បញ្ចូលជំហានដែលអ្នកបានធ្វើ និងអ្វីដែលអ្នករំពឹងថានឹងកើតឡើង។",
  "Industry": "ឧស្សាហកម្ម",
  "Interview accepted.": "បានទទួលយកសម្ភាសន៍។",
  "Interview declined.": "បានបដិសេធសម្ភាសន៍។",
  "Interview round (optional)": "វគ្គសម្ភាសន៍ (មិនចាំបាច់)",
  "It will be removed for both people.": "វានឹងត្រូវលុបសម្រាប់អ្នកទាំងពីរ។",
  "JPEG, PNG, GIF or WebP · up to 5 MB": "JPEG, PNG, GIF ឬ WebP · រហូតដល់ ៥ MB",
  "Job": "ការងារ",
  "Job title": "មុខតំណែង",
  "Keep": "រក្សាទុក",
  "Keep account": "រក្សាគណនី",
  "Keep blocked": "បន្តទប់ស្កាត់",
  "Keep it": "រក្សាវាទុក",
  "Keep them": "រក្សាទាំងនេះទុក",
  "Kept here until you like them or take them off the list.":
      "រក្សានៅទីនេះរហូតអ្នកចុចចូលចិត្ត ឬដកចេញពីបញ្ជី។",
  "Khmer, English": "ខ្មែរ អង់គ្លេស",
  "Languages": "ភាសា",
  "Last name": "នាមត្រកូល",
  "Layout": "ប្លង់",
  "Like": "ចូលចិត្ត",
  "Like a candidate to show interest. If they like you back, it's a match.":
      "ចុចចូលចិត្តបេក្ខជនដើម្បីបង្ហាញចំណាប់អារម្មណ៍។ បើពួកគេចូលចិត្តអ្នកវិញ នោះមានការផ្គូផ្គង។",
  "Like a company to show interest. If they like you back, it's a match.":
      "ចុចចូលចិត្តក្រុមហ៊ុនដើម្បីបង្ហាញចំណាប់អារម្មណ៍។ បើពួកគេចូលចិត្តអ្នកវិញ នោះមានការផ្គូផ្គង។",
  "Like candidates in the feed. When one likes you back, they appear here.":
      "ចុចចូលចិត្តបេក្ខជនក្នុងទំព័រដើម។ ពេលពួកគេចូលចិត្តអ្នកវិញ ពួកគេនឹងបង្ហាញនៅទីនេះ។",
  "Like companies in the feed. When one likes you back, they appear here.":
      "ចុចចូលចិត្តក្រុមហ៊ុនក្នុងទំព័រដើម។ ពេលពួកគេចូលចិត្តអ្នកវិញ ពួកគេនឹងបង្ហាញនៅទីនេះ។",
  "Links": "តំណ",
  "Local draft recovered. Save it to your account.":
      "បានស្តារសេចក្តីព្រាងលើឧបករណ៍នេះ។ រក្សាទុកក្នុងគណនីរបស់អ្នក។",
  "Log in with your phone": "ចូលគណនីដោយលេខទូរស័ព្ទ",
  "Logo": "ស្លាកសញ្ញា",
  "Mark all read": "សម្គាល់ទាំងអស់ថាបានអាន",
  "Match score": "ពិន្ទុផ្គូផ្គង",
  "Matched profile": "ប្រវត្តិរូបដែលបានផ្គូផ្គង",
  "Matches scope names exactly": "ត្រូវគ្នាតាមឈ្មោះវិស័យពិតប្រាកដ",
  "Matches, applications and interview invites land here.":
      "ការផ្គូផ្គង ពាក្យស្នើសុំ និងការអញ្ជើញសម្ភាសន៍នឹងបង្ហាញនៅទីនេះ។",
  "Matching is for talent and companies. Finish your profile to start.":
      "ការផ្គូផ្គងសម្រាប់បេក្ខជន និងក្រុមហ៊ុន។ បំពេញប្រវត្តិរូបដើម្បីចាប់ផ្តើម។",
  "Matching ranks candidates against your career scopes. You can post open roles and add your logo from your profile later.":
      "ការផ្គូផ្គងចាត់លំដាប់បេក្ខជនតាមវិស័យការងាររបស់អ្នក។ អ្នកអាចប្រកាសតួនាទី និងបន្ថែមស្លាកសញ្ញាពីប្រវត្តិរូបនៅពេលក្រោយ។",
  "Matching ranks roles against your career scopes and skills. You can add experience, education and your CV from your profile later.":
      "ការផ្គូផ្គងចាត់លំដាប់តួនាទីតាមវិស័យការងារ និងជំនាញរបស់អ្នក។ អ្នកអាចបន្ថែមបទពិសោធន៍ ការអប់រំ និង CV ពីប្រវត្តិរូបនៅពេលក្រោយ។",
  "Maximum salary": "ប្រាក់ខែអតិបរមា",
  "Meeting link": "តំណចូលសម្ភាសន៍",
  "Meeting link copied.": "បានចម្លងតំណចូលសម្ភាសន៍។",
  "Message": "សារ",
  "Message a match": "ផ្ញើសារទៅអ្នកដែលបានផ្គូផ្គង",
  "Message actions": "សកម្មភាពសារ",
  "Message deleted": "បានលុបសារ",
  "Messages need attention": "សារត្រូវការការពិនិត្យ",
  "Minimum salary": "ប្រាក់ខែអប្បបរមា",
  "More could not load": "មិនអាចផ្ទុកបន្ថែមបាន",
  "Move": "ផ្លាស់ប្តូរ",
  "Move an applicant to start measuring response time.":
      "ផ្លាស់ប្តូរដំណាក់កាលបេក្ខជនដើម្បីចាប់ផ្តើមវាស់ពេលឆ្លើយតប។",
  "Move applicants through each hiring stage":
      "ផ្លាស់ប្តូរបេក្ខជនតាមដំណាក់កាលជ្រើសរើសនីមួយៗ",
  "Move down": "ផ្លាស់ចុះក្រោម",
  "Move stage": "ប្តូរដំណាក់កាល",
  "Move up": "ផ្លាស់ឡើងលើ",
  "My resumes": "ប្រវត្តិរូបការងាររបស់ខ្ញុំ",
  "Name": "ឈ្មោះ",
  "Name, role or skill": "ឈ្មោះ តួនាទី ឬជំនាញ",
  "Names, roles and skills across every candidate.":
      "ឈ្មោះ តួនាទី និងជំនាញរបស់បេក្ខជនទាំងអស់។",
  "Neither of you appears in the other's feed or search.":
      "អ្នកទាំងពីរមិនបង្ហាញក្នុងទំព័រដើម ឬការស្វែងរករបស់គ្នាទេ។",
  "New password": "ពាក្យសម្ងាត់ថ្មី",
  "New profiles appear here as they join. Pull down to check again.":
      "ប្រវត្តិរូបថ្មីបង្ហាញនៅពេលចូលរួម។ អូសចុះក្រោមដើម្បីពិនិត្យម្តងទៀត។",
  "New resume": "ប្រវត្តិរូបការងារថ្មី",
  "New resume — save to keep it":
      "ប្រវត្តិរូបការងារថ្មី — រក្សាទុកដើម្បីរក្សាវា",
  "No company photos yet.": "មិនទាន់មានរូបថតក្រុមហ៊ុន។",
  "No feed for this account": "មិនមានទំព័រដើមសម្រាប់គណនីនេះ",
  "No matches on this account": "មិនមានការផ្គូផ្គងក្នុងគណនីនេះ",
  "No profile on this account": "មិនមានប្រវត្តិរូបក្នុងគណនីនេះ",
  "No recent profile viewers yet.": "មិនទាន់មានអ្នកមើលប្រវត្តិរូបថ្មីៗ។",
  "No saved profiles for this account":
      "មិនមានប្រវត្តិរូបដែលបានរក្សាទុកក្នុងគណនីនេះ",
  "No search on this account": "មិនមានការស្វែងរកសម្រាប់គណនីនេះ",
  "No stage changes yet.": "មិនទាន់មានការប្តូរដំណាក់កាល។",
  "Notes could not load.": "មិនអាចផ្ទុកកំណត់សម្គាល់បាន។",
  "Nothing in your career scopes": "មិនមានលទ្ធផលក្នុងវិស័យការងាររបស់អ្នក",
  "On-site": "ធ្វើការនៅកន្លែង",
  "Online": "កំពុងនៅលើបណ្តាញ",
  "Only my career scopes": "តែវិស័យការងាររបស់ខ្ញុំ",
  "Open": "បើក",
  "Open a saved search with the same filters, or choose how often new matches reach your inbox.":
      "បើកការស្វែងរកដែលបានរក្សាទុកជាមួយលក្ខខណ្ឌដដែល ឬជ្រើសរើសភាពញឹកញាប់នៃការផ្ញើការផ្គូផ្គងថ្មីមកអ៊ីមែល។",
  "Open positions belong to company profiles.":
      "មុខតំណែងបើកទទួលជារបស់ប្រវត្តិរូបក្រុមហ៊ុន។",
  "Openings": "ចំនួនជ្រើសរើស",
  "Optimize resume": "កែលម្អប្រវត្តិរូបការងារ",
  "Optional": "មិនចាំបាច់",
  "Other members may see that you viewed their profile.":
      "សមាជិកផ្សេងអាចឃើញថាអ្នកបានមើលប្រវត្តិរូបពួកគេ។",
  "Other members will not see your identity in their profile viewers.":
      "សមាជិកផ្សេងមិនឃើញអត្តសញ្ញាណអ្នកក្នុងបញ្ជីអ្នកមើលប្រវត្តិរូបទេ។",
  "PDF or Word · up to 10 MB": "PDF ឬ Word · រហូតដល់ ១០ MB",
  "Password is required": "ត្រូវបញ្ចូលពាក្យសម្ងាត់",
  "Password is too long": "ពាក្យសម្ងាត់វែងពេក",
  "Password must be at least 8 characters":
      "ពាក្យសម្ងាត់ត្រូវមានយ៉ាងហោចណាស់ ៨ តួអក្សរ",
  "Password only": "ពាក្យសម្ងាត់តែប៉ុណ្ណោះ",
  "Password updated. Log in with your new password.":
      "បានប្តូរពាក្យសម្ងាត់។ ចូលគណនីដោយពាក្យសម្ងាត់ថ្មី។",
  "Paste the token": "បិទភ្ជាប់លេខកូដ",
  "Paste your experience and skills": "បិទភ្ជាប់បទពិសោធន៍ និងជំនាញរបស់អ្នក",
  "Personal details": "ព័ត៌មានផ្ទាល់ខ្លួន",
  "Phone": "ទូរស័ព្ទ",
  "Phone (optional)": "ទូរស័ព្ទ (មិនចាំបាច់)",
  "Photo": "រូបថត",
  "Photo position": "ទីតាំងរូបថត",
  "Please try again.": "សូមព្យាយាមម្តងទៀត។",
  "Polish draft": "កែលម្អសេចក្តីព្រាង",
  "Position": "មុខតំណែង",
  "Post a role before managing applicants and interviews.":
      "ប្រកាសតួនាទីមុនគ្រប់គ្រងបេក្ខជន និងសម្ភាសន៍។",
  "Preview PDF": "មើល PDF",
  "Private notes": "កំណត់សម្គាល់ឯកជន",
  "Profession": "វិជ្ជាជីវៈ",
  "Profile completion": "ការបំពេញប្រវត្តិរូប",
  "Profile privacy": "ឯកជនភាពប្រវត្តិរូប",
  "Profiles belong to talent and companies.":
      "ប្រវត្តិរូបជារបស់បេក្ខជន និងក្រុមហ៊ុន។",
  "Profiles belong to talent and companies. Finish signing up to get one.":
      "ប្រវត្តិរូបជារបស់បេក្ខជន និងក្រុមហ៊ុន។ បញ្ចប់ការចុះឈ្មោះដើម្បីទទួលបានប្រវត្តិរូប។",
  "Protected": "បានការពារ",
  "RECOMMENDED": "បានណែនាំ",
  "Ranked against your open roles and career scopes":
      "ចាត់លំដាប់តាមតួនាទីបើកទទួល និងវិស័យការងាររបស់អ្នក",
  "Ranked against your skills and career scopes":
      "ចាត់លំដាប់តាមជំនាញ និងវិស័យការងាររបស់អ្នក",
  "React": "ប្រតិកម្ម",
  "React to message": "ប្រតិកម្មចំពោះសារ",
  "Read": "បានអាន",
  "Recent viewers": "អ្នកមើលថ្មីៗ",
  "Recommended for you": "បានណែនាំសម្រាប់អ្នក",
  "Record voice message": "ថតសារសំឡេង",
  "Recording voice message…": "កំពុងថតសារសំឡេង…",
  "Refine bio": "កែលម្អជីវប្រវត្តិ",
  "Refresh AI allowance": "ផ្ទុកចំនួនប្រើប្រាស់ AI ឡើងវិញ",
  "Reload": "ផ្ទុកឡើងវិញ",
  "Remote": "ធ្វើការពីចម្ងាយ",
  "Remove": "ដកចេញ",
  "Remove attachment": "ដកឯកសារភ្ជាប់ចេញ",
  "Remove experience": "ដកបទពិសោធន៍ចេញ",
  "Remove imported entry": "ដកព័ត៌មានដែលបាននាំចូលចេញ",
  "Remove reaction": "ដកប្រតិកម្មចេញ",
  "Rename": "ប្តូរឈ្មោះ",
  "Rename resume": "ប្តូរឈ្មោះប្រវត្តិរូបការងារ",
  "Repeat the new password": "បញ្ចូលពាក្យសម្ងាត់ថ្មីម្តងទៀត",
  "Repeat the password": "បញ្ចូលពាក្យសម្ងាត់ម្តងទៀត",
  "Replace": "ជំនួស",
  "Reply": "ឆ្លើយតប",
  "Replying to": "កំពុងឆ្លើយតបទៅ",
  "Report": "រាយការណ៍",
  "Report {0}": "រាយការណ៍ {0}",
  "Reporting does not block them. Block separately if you also want them gone from your feed.":
      "ការរាយការណ៍មិនទប់ស្កាត់ពួកគេទេ។ ទប់ស្កាត់ដាច់ដោយឡែកបើចង់ដកពួកគេពីទំព័រដើម។",
  "Required": "ចាំបាច់",
  "Required skills": "ជំនាញដែលតម្រូវ",
  "Requirements": "លក្ខខណ្ឌតម្រូវ",
  "Reset token": "លេខកូដកំណត់ឡើងវិញ",
  "Reset your password": "កំណត់ពាក្យសម្ងាត់របស់អ្នកឡើងវិញ",
  "Resets {0} (local time)": "កំណត់ឡើងវិញនៅ {0} (ពេលវេលាតំបន់)",
  "Resume design": "ការរចនាប្រវត្តិរូបការងារ",
  "Resume from text": "ប្រវត្តិរូបការងារពីអត្ថបទ",
  "Resume name": "ឈ្មោះប្រវត្តិរូបការងារ",
  "Retry save": "ព្យាយាមរក្សាទុកម្តងទៀត",
  "Review AI suggestions for accuracy before applying them.":
      "ពិនិត្យភាពត្រឹមត្រូវនៃការណែនាំ AI មុនអនុវត្ត។",
  "Review resume details": "ពិនិត្យព័ត៌មានប្រវត្តិរូបការងារ",
  "Review the draft for accuracy and edit it before using it. Nothing is saved or sent from this screen.":
      "ពិនិត្យភាពត្រឹមត្រូវនៃសេចក្តីព្រាង និងកែសម្រួលមុនប្រើ។ ទំព័រនេះមិនរក្សាទុក ឬផ្ញើអ្វីទេ។",
  "Review the time, location, meeting link, and current response status.":
      "ពិនិត្យពេលវេលា ទីតាំង តំណចូលសម្ភាសន៍ និងស្ថានភាពឆ្លើយតបបច្ចុប្បន្ន។",
  "Role, skill or keyword": "តួនាទី ជំនាញ ឬពាក្យគន្លឹះ",
  "Roles you apply for appear here, with where each one stands.":
      "តួនាទីដែលអ្នកដាក់ពាក្យនឹងបង្ហាញនៅទីនេះជាមួយស្ថានភាពនីមួយៗ។",
  "Run a job search, then use Save search to keep its filters.":
      "ស្វែងរកការងារ រួចប្រើ «រក្សាទុកការស្វែងរក» ដើម្បីរក្សាលក្ខខណ្ឌស្វែងរក។",
  "STEP {0} OF {1}": "ជំហាន {0} ក្នុងចំណោម {1}",
  "Save as new resume": "រក្សាទុកជាប្រវត្តិរូបការងារថ្មី",
  "Save changes": "រក្សាទុកការកែប្រែ",
  "Save resume": "រក្សាទុកប្រវត្តិរូបការងារ",
  "Save search": "រក្សាទុកការស្វែងរក",
  "Save this search": "រក្សាទុកការស្វែងរកនេះ",
  "Saved searches": "ការស្វែងរកដែលបានរក្សាទុក",
  "Saved to your account": "បានរក្សាទុកក្នុងគណនីរបស់អ្នក",
  "Saving is for talent and companies. Finish your profile to start saving.":
      "ការរក្សាទុកសម្រាប់បេក្ខជន និងក្រុមហ៊ុន។ បំពេញប្រវត្តិរូបដើម្បីចាប់ផ្តើមរក្សាទុក។",
  "Saving to your account…": "កំពុងរក្សាទុកក្នុងគណនីរបស់អ្នក…",
  "Say hello to start the conversation.": "និយាយសួស្តីដើម្បីចាប់ផ្តើមសន្ទនា។",
  "Schedule": "កាលវិភាគ",
  "Schedule account deletion": "កំណត់ពេលលុបគណនី",
  "Schedule account deletion?": "កំណត់ពេលលុបគណនី?",
  "Schedule deletion": "កំណត់ពេលលុប",
  "Schedule interview": "កំណត់ពេលសម្ភាសន៍",
  "Schedule one from an applicant’s details.":
      "កំណត់ពេលសម្ភាសន៍ពីព័ត៌មានបេក្ខជន។",
  "Search for a role": "ស្វែងរកតួនាទី",
  "Search for talent": "ស្វែងរកបេក្ខជន",
  "Search is for talent and companies. Finish signing up to use it.":
      "ការស្វែងរកសម្រាប់បេក្ខជន និងក្រុមហ៊ុន។ បញ្ចប់ការចុះឈ្មោះដើម្បីប្រើ។",
  "Search saved.": "បានរក្សាទុកការស្វែងរក។",
  "Section headings": "ចំណងជើងផ្នែក",
  "Section order": "លំដាប់ផ្នែក",
  "Selected text fields replace form values. Skills, career scopes, work history and education are added to your draft. Your login details stay the same. Nothing is saved until you submit the form.":
      "អត្ថបទដែលបានជ្រើសរើសនឹងជំនួសតម្លៃក្នុងទម្រង់។ ជំនាញ វិស័យការងារ បទពិសោធន៍ និងការអប់រំនឹងត្រូវបន្ថែមក្នុងសេចក្តីព្រាង។ ព័ត៌មានចូលគណនីនៅដដែល។ ទិន្នន័យរក្សាទុកនៅពេលអ្នកដាក់ស្នើទម្រង់។",
  "Send application": "ផ្ញើពាក្យស្នើសុំ",
  "Send message": "ផ្ញើសារ",
  "Send report": "ផ្ញើរបាយការណ៍",
  "Send reset token": "ផ្ញើលេខកូដកំណត់ឡើងវិញ",
  "Sent": "បានផ្ញើ",
  "Set up two-step verification": "រៀបចំការផ្ទៀងផ្ទាត់ពីរជំហាន",
  "Setup key copied": "បានចម្លងលេខសម្ងាត់រៀបចំ",
  "Showing every match instead, so these are not narrowed.":
      "កំពុងបង្ហាញការផ្គូផ្គងទាំងអស់ ដូច្នេះលទ្ធផលទាំងនេះមិនត្រូវបានចម្រាញ់ទេ។",
  "Sidebar sections": "ផ្នែកក្នុងរបារចំហៀង",
  "Signing in asks for a code from your authenticator app.":
      "ការចូលគណនីតម្រូវលេខកូដពីកម្មវិធីផ្ទៀងផ្ទាត់របស់អ្នក។",
  "Skills (one per line)": "ជំនាញ (មួយក្នុងមួយបន្ទាត់)",
  "Skills style": "រចនាប័ទ្មជំនាញ",
  "Social links": "តំណបណ្តាញសង្គម",
  "Some details are missing — check the highlighted fields.":
      "ព័ត៌មានខ្លះខ្វះ — ពិនិត្យវាលដែលបានបន្លិច។",
  "Spacing": "ចន្លោះ",
  "Start date": "កាលបរិច្ឆេទចាប់ផ្តើម",
  "Start over": "ចាប់ផ្តើមឡើងវិញ",
  "Status history": "ប្រវត្តិស្ថានភាព",
  "Suggested summary": "សេចក្តីសង្ខេបដែលបានណែនាំ",
  "Summary": "សេចក្តីសង្ខេប",
  "Summary style": "រចនាប័ទ្មសេចក្តីសង្ខេប",
  "Summary · AI draft": "សេចក្តីសង្ខេប · សេចក្តីព្រាង AI",
  "Take a copy of your information or manage account deletion.":
      "យកច្បាប់ចម្លងព័ត៌មានរបស់អ្នក ឬគ្រប់គ្រងការលុបគណនី។",
  "Talent": "បេក្ខជន",
  "Talent that fits your roles": "បេក្ខជនដែលសមនឹងតួនាទីរបស់អ្នក",
  "Talent who liked you back": "បេក្ខជនដែលចូលចិត្តអ្នកវិញ",
  "Talent you saved": "បេក្ខជនដែលអ្នកបានរក្សាទុក",
  "Talk with the people you have matched with.":
      "សន្ទនាជាមួយអ្នកដែលបានផ្គូផ្គង។",
  "Tap the bookmark on any candidate in the feed to keep them here.":
      "ចុចសញ្ញារក្សាទុកលើបេក្ខជនក្នុងទំព័រដើម ដើម្បីរក្សាពួកគេនៅទីនេះ។",
  "Tap the bookmark on any company in the feed to keep it here.":
      "ចុចសញ្ញារក្សាទុកលើក្រុមហ៊ុនក្នុងទំព័រដើម ដើម្បីរក្សាវានៅទីនេះ។",
  "Technical round, HR interview…": "វគ្គបច្ចេកទេស សម្ភាសន៍ធនធានមនុស្ស…",
  "Tell us what is wrong. They are not told.":
      "ប្រាប់យើងពីបញ្ហា។ ពួកគេមិនត្រូវបានជូនដំណឹងទេ។",
  "Template": "គំរូ",
  "The feed shows companies to talent and talent to companies. Finish your profile to see yours.":
      "ទំព័រដើមបង្ហាញក្រុមហ៊ុនដល់បេក្ខជន និងបេក្ខជនដល់ក្រុមហ៊ុន។ បំពេញប្រវត្តិរូបដើម្បីមើលទំព័រដើមរបស់អ្នក។",
  "The fields you work in": "វិស័យដែលអ្នកធ្វើការ",
  "The server history limit has been reached.":
      "បានដល់កំណត់ប្រវត្តិរបស់ម៉ាស៊ីនមេ។",
  "The work areas this profile belongs to":
      "វិស័យការងារដែលប្រវត្តិរូបនេះស្ថិតក្នុង",
  "These changes have not been saved to your account.":
      "ការកែប្រែទាំងនេះមិនទាន់បានរក្សាទុកក្នុងគណនីរបស់អ្នកទេ។",
  "This confirms the app is set up before it is required.":
      "នេះបញ្ជាក់ថាកម្មវិធីត្រូវបានរៀបចំរួច មុនត្រូវការប្រើ។",
  "This job could not load": "មិនអាចផ្ទុកការងារនេះបាន",
  "This profile could not load": "មិនអាចផ្ទុកប្រវត្តិរូបនេះបាន",
  "This removes the stored file from your profile.":
      "នេះដកឯកសារដែលបានរក្សាទុកចេញពីប្រវត្តិរូបរបស់អ្នក។",
  "Title": "ចំណងជើង",
  "Titles, descriptions and skills across every open posting.":
      "ចំណងជើង ការពិពណ៌នា និងជំនាញក្នុងប្រកាសបើកទទួលទាំងអស់។",
  "Tokens expire. If yours has, go back and request a new one.":
      "លេខកូដមានថ្ងៃផុតកំណត់។ បើផុតកំណត់ ត្រឡប់ក្រោយហើយស្នើសុំថ្មី។",
  "Top positions": "មុខតំណែងសំខាន់ៗ",
  "Turn it off": "បិទវា",
  "Turn off two-step verification": "បិទការផ្ទៀងផ្ទាត់ពីរជំហាន",
  "Turn on two-step verification": "បើកការផ្ទៀងផ្ទាត់ពីរជំហាន",
  "Turning one off silences every category below it":
      "ការបិទមួយនឹងបិទការជូនដំណឹងគ្រប់ប្រភេទនៅខាងក្រោមវា",
  "Two-step verification is off.": "ការផ្ទៀងផ្ទាត់ពីរជំហានបានបិទ។",
  "Two-step verification is on.": "ការផ្ទៀងផ្ទាត់ពីរជំហានបានបើក។",
  "Typography": "ទម្រង់អក្សរ",
  "Unblock": "ឈប់ទប់ស្កាត់",
  "Unblock {0}?": "ឈប់ទប់ស្កាត់ {0}?",
  "Unmatch": "បញ្ឈប់ការផ្គូផ្គង",
  "Upcoming and completed interviews": "សម្ភាសន៍ខាងមុខ និងដែលបានបញ្ចប់",
  "Update password": "ប្តូរពាក្យសម្ងាត់",
  "Updated {0}": "បានកែប្រែ {0}",
  "Upload": "ផ្ទុកឡើង",
  "Upload a PDF up to 5 MB to prefill your profile. Review extracted details before applying them.":
      "ផ្ទុក PDF រហូតដល់ ៥ MB ដើម្បីបំពេញប្រវត្តិរូបជាមុន។ ពិនិត្យព័ត៌មានដែលបានស្រង់មុនអនុវត្ត។",
  "Use a color in #RRGGBB format.": "ប្រើពណ៌តាមទម្រង់ #RRGGBB។",
  "Use template design": "ប្រើការរចនាគំរូ",
  "Use this draft": "ប្រើសេចក្តីព្រាងនេះ",
  "Use up to 100 skills, each no longer than 200 characters.":
      "ប្រើជំនាញរហូតដល់ ១០០ ដែលមួយៗមិនលើស ២០០ តួអក្សរ។",
  "Use your profiles to understand this match and prepare your next move.":
      "ប្រើប្រវត្តិរូបទាំងពីរដើម្បីយល់ការផ្គូផ្គងនេះ និងត្រៀមជំហានបន្ទាប់។",
  "Used for recommendations and matching": "ប្រើសម្រាប់ការណែនាំ និងការផ្គូផ្គង",
  "Username": "ឈ្មោះអ្នកប្រើ",
  "Values": "តម្លៃ",
  "Verify email": "ផ្ទៀងផ្ទាត់អ៊ីមែល",
  "Verify later": "ផ្ទៀងផ្ទាត់ពេលក្រោយ",
  "Verify your email": "ផ្ទៀងផ្ទាត់អ៊ីមែលរបស់អ្នក",
  "View interview schedule": "មើលកាលវិភាគសម្ភាសន៍",
  "Voice call": "ការហៅសំឡេង",
  "We will text you a six-digit code to confirm the number.":
      "យើងនឹងផ្ញើលេខកូដប្រាំមួយខ្ទង់តាមសារដើម្បីបញ្ជាក់លេខទូរស័ព្ទ។",
  "Website (optional)": "គេហទំព័រ (មិនចាំបាច់)",
  "What each kind of notification may use": "បណ្តាញដែលការជូនដំណឹងនីមួយៗអាចប្រើ",
  "What happened?": "មានអ្វីកើតឡើង?",
  "What matching is ranked against": "លក្ខខណ្ឌសម្រាប់ចាត់លំដាប់ការផ្គូផ្គង",
  "What talent sees on your card": "ព័ត៌មានដែលបេក្ខជនមើលឃើញលើកាតរបស់អ្នក",
  "What this posting asks for": "អ្វីដែលប្រកាសនេះតម្រូវ",
  "What you do, and what it is like to work there":
      "ការងាររបស់ក្រុមហ៊ុន និងបរិយាកាសការងារនៅទីនោះ",
  "Where the company is based": "ទីតាំងក្រុមហ៊ុន",
  "Where you are based": "ទីតាំងរបស់អ្នក",
  "Why you are a fit (optional)": "ហេតុអ្វីអ្នកសមនឹងតួនាទីនេះ (មិនចាំបាច់)",
  "Withdraw": "ដកពាក្យ",
  "Withdraw this application?": "ដកពាក្យស្នើសុំនេះ?",
  "Withdrawing keeps the record; it does not delete it.":
      "ការដកពាក្យរក្សាប្រវត្តិទុក មិនលុបវាទេ។",
  "Work": "ការងារ",
  "Work history": "ប្រវត្តិការងារ",
  "Work mode": "របៀបធ្វើការ",
  "Write a message": "សរសេរសារ",
  "Write bio with AI": "សរសេរជីវប្រវត្តិដោយ AI",
  "Write with AI": "សរសេរដោយ AI",
  "YYYY-MM-DD": "ឆ្នាំ-ខែ-ថ្ងៃ",
  "Year": "ឆ្នាំ",
  "You": "អ្នក",
  "You are telling the company you are no longer interested in {0}. The application stays in this list, marked withdrawn. Applying again revives this same application rather than starting a second one.":
      "អ្នកកំពុងប្រាប់ក្រុមហ៊ុនថាមិនមានចំណាប់អារម្មណ៍លើ {0} ទៀតទេ។ ពាក្យស្នើសុំនៅក្នុងបញ្ជីនេះ ដោយសម្គាល់ថាបានដកពាក្យ។ ការដាក់ពាក្យម្តងទៀតធ្វើឱ្យពាក្យនេះសកម្មវិញ ជំនួសការបង្កើតថ្មី។",
  "You can request a new code in {0}s":
      "អ្នកអាចស្នើសុំលេខកូដថ្មីក្នុង {0} វិនាទី",
  "You disappear from each other's feed and search.":
      "អ្នកទាំងពីរនឹងមិនបង្ហាញក្នុងទំព័រដើម និងការស្វែងរករបស់គ្នាទៀតទេ។",
  "You will be able to see each other again, in the feed and in search. They are not told either way.":
      "អ្នកទាំងពីរនឹងអាចមើលឃើញគ្នាម្តងទៀតក្នុងទំព័រដើម និងការស្វែងរក។ ពួកគេមិនត្រូវបានជូនដំណឹងទេ។",
  "You will need an authenticator app such as Google Authenticator, Microsoft Authenticator or 1Password.":
      "អ្នកត្រូវការកម្មវិធីផ្ទៀងផ្ទាត់ដូចជា Google Authenticator, Microsoft Authenticator ឬ 1Password។",
  "You will not see each other in the feed or in search, and neither of you can like the other. They are not told. You can undo this in Settings.":
      "អ្នកទាំងពីរនឹងមិនឃើញគ្នាក្នុងទំព័រដើម ឬការស្វែងរក ហើយមិនអាចចុចចូលចិត្តគ្នាបានទេ។ ពួកគេមិនត្រូវបានជូនដំណឹងទេ។ អ្នកអាចលុបចោលការទប់ស្កាត់ក្នុងការកំណត់។",
  "You will sign in with this email. We will send a code to it to confirm it is yours.":
      "អ្នកនឹងចូលគណនីដោយអ៊ីមែលនេះ។ យើងនឹងផ្ញើលេខកូដដើម្បីបញ្ជាក់ថាជាអ៊ីមែលរបស់អ្នក។",
  "You withdrew this one. Applying again revives it.":
      "អ្នកបានដកពាក្យនេះ។ ការដាក់ពាក្យម្តងទៀតនឹងធ្វើឱ្យវាសកម្មវិញ។",
  "You'll need it to log in again. We'll send a code to {0}.":
      "អ្នកនឹងត្រូវការវាដើម្បីចូលគណនីម្តងទៀត។ យើងនឹងផ្ញើលេខកូដទៅ {0}។",
  "You're all caught up": "អ្នកបានមើលទាំងអស់ហើយ",
  "Your account is scheduled for permanent deletion on {0}. You can continue using it and cancel before then.":
      "គណនីរបស់អ្នកនឹងត្រូវលុបជាអចិន្ត្រៃយ៍នៅ {0}។ អ្នកអាចបន្តប្រើ និងបោះបង់មុនពេលនោះ។",
  "Your account stays available for 30 days. After that, it and its associated data will be permanently deleted. You can cancel during the grace period.":
      "គណនីរបស់អ្នកនៅអាចប្រើបានរយៈពេល ៣០ ថ្ងៃ។ បន្ទាប់មកគណនី និងទិន្នន័យពាក់ព័ន្ធនឹងត្រូវលុបជាអចិន្ត្រៃយ៍។ អ្នកអាចបោះបង់ក្នុងអំឡុងពេលនេះ។",
  "Your company profile could not load":
      "មិនអាចផ្ទុកប្រវត្តិរូបក្រុមហ៊ុនរបស់អ្នកបាន",
  "Your notification settings could not load":
      "មិនអាចផ្ទុកការកំណត់ការជូនដំណឹងបាន",
  "Your saved profiles could not load":
      "មិនអាចផ្ទុកប្រវត្តិរូបដែលបានរក្សាទុកបាន",
  "Your saved resumes will appear here. Create one to get started.":
      "ប្រវត្តិរូបការងារដែលបានរក្សាទុកនឹងបង្ហាញនៅទីនេះ។ បង្កើតមួយដើម្បីចាប់ផ្តើម។",
  "Your sign-in details": "ព័ត៌មានចូលគណនីរបស់អ្នក",
  "Your visibility": "ភាពមើលឃើញរបស់អ្នក",
  "amber": "ពណ៌ទឹកក្រូច",
  "balanced": "មានតុល្យភាព",
  "bar": "របារ",
  "cards": "កាត",
  "careerScopes": "វិស័យការងារ",
  "center": "កណ្តាល",
  "centered": "នៅកណ្តាល",
  "chips": "ស្លាកមូល",
  "cobalt": "ពណ៌ខៀវ",
  "compact": "ចង្អៀត",
  "e.g. 50": "ឧ. ៥០",
  "e.g. Financial Services": "ឧ. សេវាហិរញ្ញវត្ថុ",
  "e.g. Frontend Developer": "ឧ. អ្នកអភិវឌ្ឍផ្នែកខាងមុខ",
  "e.g. React, then press +": "ឧ. React រួចចុច +",
  "e.g. Senior design roles": "ឧ. តួនាទីអ្នករចនាជាន់ខ្ពស់",
  "education": "ការអប់រំ",
  "emerald": "ពណ៌បៃតង",
  "end": "ចុង",
  "experience": "បទពិសោធន៍",
  "geometric": "អក្សរធរណីមាត្រ",
  "graphite": "ពណ៌ប្រផេះ",
  "grid": "ក្រឡា",
  "highlight": "បន្លិច",
  "humanist": "អក្សរបែបធម្មជាតិ",
  "left-sidebar": "របារចំហៀងខាងឆ្វេង",
  "line": "បន្ទាត់",
  "list": "បញ្ជី",
  "midnight": "ពណ៌ខៀវងងឹត",
  "minimal": "សាមញ្ញ",
  "mono": "អក្សរទទឹងស្មើគ្នា",
  "narrow": "តូច",
  "none": "គ្មាន",
  "ocean": "ពណ៌សមុទ្រ",
  "pill": "គ្រាប់មូល",
  "plain": "ធម្មតា",
  "quote": "សម្រង់",
  "right-sidebar": "របារចំហៀងខាងស្តាំ",
  "rose": "ពណ៌ផ្កាឈូក",
  "rounded": "ជ្រុងមូល",
  "s": "វិនាទី",
  "sand": "ពណ៌ខ្សាច់",
  "sans": "អក្សរគ្មានជើង",
  "serif": "អក្សរមានជើង",
  "side-band": "ខ្សែពណ៌ចំហៀង",
  "single": "មួយជួរឈរ",
  "skills": "ជំនាញ",
  "soft": "ស្រាល",
  "solid": "ពណ៌ពេញ",
  "spacious": "ទូលាយ",
  "split": "បែងចែក",
  "square": "ជ្រុងការេ",
  "stacked": "តម្រៀបជាស្រទាប់",
  "start": "ដើម",
  "summary": "សេចក្តីសង្ខេប",
  "timeline": "ខ្សែពេលវេលា",
  "top-band": "ខ្សែពណ៌ខាងលើ",
  "two-column": "ពីរជួរឈរ",
  "violet": "ពណ៌ស្វាយ",
  "wide": "ធំ",
  "{0} GAP · ~{1} weeks": "កង្វះ {0} · ប្រហែល {1} សប្តាហ៍",
  "{0} emails": "អ៊ីមែល {0}",
  "{0} from resume ({1})": "{0} ពីប្រវត្តិរូបការងារ ({1})",
  "{0} of {1} AI requests remaining today":
      "នៅសល់ {0} ក្នុងចំណោម {1} សំណើ AI ថ្ងៃនេះ",
  "{0} of {1} CV generations remaining":
      "នៅសល់ {0} ក្នុងចំណោម {1} ការបង្កើត CV",
  "{0} selected": "បានជ្រើសរើស {0}",
  "{0} will be removed from search and matching.":
      "{0} នឹងត្រូវដកចេញពីការស្វែងរក និងការផ្គូផ្គង។",
  "{0} · Answer tip": "{0} · គន្លឹះឆ្លើយតប",
  "{0}% match": "ផ្គូផ្គង {0}%",
  "{0}% of it from overlapping skills": "{0}% មកពីជំនាញត្រូវគ្នា",
  "“{0}” and its email schedule will be removed.":
      "«{0}» និងកាលវិភាគអ៊ីមែលរបស់វានឹងត្រូវលុប។",
  "All open roles": "តួនាទីបើកទទួលទាំងអស់",
  "Not uploaded": "មិនទាន់ផ្ទុកឡើង",
  "Offline": "ក្រៅបណ្តាញ",
  "Reconnecting…": "កំពុងតភ្ជាប់ឡើងវិញ…",
  "Typing…": "កំពុងវាយ…",
  "Untitled": "គ្មានចំណងជើង",
  "Reload saved resume": "ផ្ទុកប្រវត្តិរូបការងារដែលបានរក្សាទុកឡើងវិញ",
  "Discard edits and reload?": "បោះបង់ការកែប្រែ ហើយផ្ទុកឡើងវិញ?",
  "This replaces local edits with the latest saved version.":
      "នេះជំនួសការកែប្រែលើឧបករណ៍នេះដោយកំណែដែលបានរក្សាទុកថ្មីបំផុត។",
  "PDF style": "រចនាប័ទ្ម PDF",
  "classic": "បុរាណ",
  "modern": "ទំនើប",
  "bold": "លេចធ្លោ",
};
