const parityProductCopy = <String, String>{
  'View profile for {0}': 'មើលប្រវត្តិរូបរបស់ {0}',
  'Matches, {0} unseen': 'ការផ្គូផ្គង {0} មិនទាន់បានមើល',
  'Notifications, {0} unread': 'ការជូនដំណឹង {0} មិនទាន់បានអាន',
  'Email preferences': 'ចំណូលចិត្តអ៊ីមែល',
  'Could not unsubscribe. Please try again.':
      'មិនអាចឈប់ជាវបានទេ។ សូមព្យាយាមម្តងទៀត។',
  'This unsubscribe link is invalid.': 'តំណឈប់ជាវនេះមិនត្រឹមត្រូវទេ។',
  'Open the link from the email footer to manage this subscription.':
      'បើកតំណនៅផ្នែកខាងក្រោមអ៊ីមែល ដើម្បីគ្រប់គ្រងការជាវនេះ។',
  'You have unsubscribed.': 'អ្នកបានឈប់ជាវហើយ។',
  'You can turn these emails back on in notification settings.':
      'អ្នកអាចបើកអ៊ីមែលទាំងនេះឡើងវិញក្នុងការកំណត់ការជូនដំណឹង។',
  'Manage notification settings': 'គ្រប់គ្រងការកំណត់ការជូនដំណឹង',
  'Unsubscribe from these emails?': 'ឈប់ជាវអ៊ីមែលទាំងនេះឬ?',
  'Confirm to stop this email category. Security and account emails stay enabled.':
      'បញ្ជាក់ដើម្បីបញ្ឈប់អ៊ីមែលប្រភេទនេះ។ អ៊ីមែលសុវត្ថិភាព និងគណនីនៅតែបើក។',
  'Unsubscribe': 'ឈប់ជាវ',
  'Administration': 'រដ្ឋបាល',
  'Platform management': 'ការគ្រប់គ្រងវេទិកា',
  'Manage accounts, review reports and keep the platform safe.':
      'គ្រប់គ្រងគណនី ពិនិត្យរបាយការណ៍ និងរក្សាសុវត្ថិភាពវេទិកា។',
  'Overview': 'ទិដ្ឋភាពទូទៅ',
  'Users': 'អ្នកប្រើប្រាស់',
  'Job moderation': 'ការត្រួតពិនិត្យការងារ',
  'User reports': 'របាយការណ៍អំពីអ្នកប្រើប្រាស់',
  'Support reports': 'របាយការណ៍ជំនួយ',
  'Audit history': 'ប្រវត្តិសវនកម្ម',
  'Accounts, reports and job moderation':
      'គណនី របាយការណ៍ និងការត្រួតពិនិត្យការងារ',
  'Only administrators can open this workspace.':
      'មានតែអ្នកគ្រប់គ្រងប៉ុណ្ណោះដែលអាចបើកកន្លែងធ្វើការនេះ។',
  'Administrative data could not be read.': 'មិនអាចអានទិន្នន័យរដ្ឋបាលបាន។',
  'Could not load administrative data.': 'មិនអាចផ្ទុកទិន្នន័យរដ្ឋបាលបាន។',
  'Choose a valid account status and future suspension date.':
      'សូមជ្រើសរើសស្ថានភាពគណនីត្រឹមត្រូវ និងកាលបរិច្ឆេទផ្អាកនៅពេលអនាគត។',
  'Choose a valid report status and a note of at most 500 characters.':
      'សូមជ្រើសរើសស្ថានភាពរបាយការណ៍ត្រឹមត្រូវ និងកំណត់សម្គាល់មិនលើសពី ៥០០ តួអក្សរ។',
  'Email or phone': 'អ៊ីមែល ឬលេខទូរស័ព្ទ',
  'Job title or company': 'មុខតំណែង ឬក្រុមហ៊ុន',
  'Target user ID (optional)': 'លេខសម្គាល់អ្នកប្រើប្រាស់គោលដៅ (មិនចាំបាច់)',
  'Role': 'តួនាទី',
  'Account status': 'ស្ថានភាពគណនី',
  'Visibility': 'ភាពមើលឃើញ',
  'Report status': 'ស្ថានភាពរបាយការណ៍',
  'Category': 'ប្រភេទ',
  'Active': 'សកម្ម',
  'Suspended': 'បានផ្អាក',
  'Banned': 'បានហាមឃាត់',
  'Candidate': 'បេក្ខជន',
  'Company': 'ក្រុមហ៊ុន',
  'Administrator': 'អ្នកគ្រប់គ្រង',
  'Pending': 'កំពុងរង់ចាំ',
  'Reviewed': 'បានពិនិត្យ',
  'Resolved': 'បានដោះស្រាយ',
  'Dismissed': 'បានបិទដោយមិនចាត់ការ',
  'Visible': 'អាចមើលឃើញ',
  'Hidden': 'បានលាក់',
  'All': 'ទាំងអស់',
  'Account suspended': 'គណនីត្រូវបានផ្អាក',
  'Account banned': 'គណនីត្រូវបានហាមឃាត់',
  'Account reinstated': 'គណនីត្រូវបានបើកឡើងវិញ',
  'Report status changed': 'ស្ថានភាពរបាយការណ៍ត្រូវបានប្តូរ',
  'Posting hidden': 'ការប្រកាសត្រូវបានលាក់',
  'Posting restored': 'ការប្រកាសត្រូវបានស្តារឡើងវិញ',
  'Spam': 'សារឥតបានការ',
  'Harassment': 'ការយាយី',
  'Fake profile': 'ប្រវត្តិរូបក្លែងក្លាយ',
  'Inappropriate content': 'មាតិកាមិនសមរម្យ',
  'Scam': 'ការឆបោក',
  'Total users': 'អ្នកប្រើប្រាស់សរុប',
  'Candidates': 'បេក្ខជន',
  'Companies': 'ក្រុមហ៊ុន',
  'Suspended accounts': 'គណនីដែលបានផ្អាក',
  'Banned accounts': 'គណនីដែលបានហាមឃាត់',
  'Pending reports': 'របាយការណ៍កំពុងរង់ចាំ',
  'New users · 7 days': 'អ្នកប្រើប្រាស់ថ្មី · ៧ ថ្ងៃ',
  'Live jobs': 'ការងារដែលកំពុងផ្សាយ',
  'Hidden jobs': 'ការងារដែលបានលាក់',
  'No results for these filters.': 'មិនមានលទ្ធផលសម្រាប់តម្រងទាំងនេះទេ។',
  'Page {page} · {total} results': 'ទំព័រ {page} · លទ្ធផល {total}',
  'Previous page': 'ទំព័រមុន',
  'Next page': 'ទំព័របន្ទាប់',
  '{count} open reports': 'របាយការណ៍មិនទាន់បិទ {count}',
  'View account details': 'មើលព័ត៌មានគណនី',
  'Job type': 'ប្រភេទការងារ',
  'Created': 'បានបង្កើត',
  'Expires': 'ផុតកំណត់',
  'Hidden at': 'លាក់នៅពេល',
  'Reason': 'មូលហេតុ',
  'Company open reports': 'របាយការណ៍មិនទាន់បិទរបស់ក្រុមហ៊ុន',
  'Restore posting': 'ស្តារការប្រកាសឡើងវិញ',
  'Hide posting': 'លាក់ការប្រកាស',
  'Reporter': 'អ្នករាយការណ៍',
  'Reported account': 'គណនីដែលត្រូវបានរាយការណ៍',
  'Page URL': 'តំណទំព័រ',
  'User agent': 'ព័ត៌មានកម្មវិធីរុករក',
  'Resolution note': 'កំណត់សម្គាល់ការដោះស្រាយ',
  'Update report': 'កែប្រែរបាយការណ៍',
  'Report ID': 'លេខសម្គាល់របាយការណ៍',
  'Target user ID': 'លេខសម្គាល់អ្នកប្រើប្រាស់គោលដៅ',
  'Confirm': 'បញ្ជាក់',
  'Status': 'ស្ថានភាព',
  'Note (optional)': 'កំណត់សម្គាល់ (មិនចាំបាច់)',
  'Give a reason between 10 and 500 characters.':
      'សូមផ្តល់មូលហេតុដែលមានពី ១០ ដល់ ៥០០ តួអក្សរ។',
  'Set suspension end date (optional)': 'កំណត់ថ្ងៃបញ្ចប់ការផ្អាក (មិនចាំបាច់)',
  'Remove end date': 'លុបថ្ងៃបញ្ចប់',
  'The reason is shown to the affected account and recorded in the audit history.':
      'មូលហេតុត្រូវបានបង្ហាញដល់គណនីដែលរងផលប៉ះពាល់ និងកត់ត្រាក្នុងប្រវត្តិសវនកម្ម។',
  'Account details': 'ព័ត៌មានគណនី',
  'User ID': 'លេខសម្គាល់អ្នកប្រើប្រាស់',
  'Email verified': 'អ៊ីមែលបានផ្ទៀងផ្ទាត់',
  'Profile complete': 'ប្រវត្តិរូបបានបំពេញ',
  'Stored account status': 'ស្ថានភាពគណនីដែលបានរក្សាទុក',
  'Suspended until': 'ផ្អាករហូតដល់',
  'Last login': 'ការចូលចុងក្រោយ',
  'Login method': 'វិធីចូល',
  'Open reports': 'របាយការណ៍មិនទាន់បិទ',
  'Change account status': 'ប្តូរស្ថានភាពគណនី',
  'Reports against this account': 'របាយការណ៍អំពីគណនីនេះ',
  'No reports against this account.': 'មិនមានរបាយការណ៍អំពីគណនីនេះទេ។',
  'Status history': 'ប្រវត្តិស្ថានភាព',
  'No status changes yet.': 'មិនទាន់មានការប្តូរស្ថានភាពទេ។',
  'Yes': 'បាទ/ចាស',
  'No': 'ទេ',
  'Dashboard': 'ផ្ទាំងទិន្នន័យ',
  'Matches, activity and profile visibility':
      'ការផ្គូផ្គង សកម្មភាព និងភាពមើលឃើញប្រវត្តិរូប',
  'Your activity at a glance': 'ទិដ្ឋភាពសង្ខេបនៃសកម្មភាពរបស់អ្នក',
  'See your matches, saved profiles and activity over the last week.':
      'មើលការផ្គូផ្គង ប្រវត្តិរូបដែលបានរក្សាទុក និងសកម្មភាពក្នុងសប្តាហ៍កន្លងមក។',
  'Profile completeness': 'ការបំពេញប្រវត្តិរូប',
  'Could not load your dashboard.': 'មិនអាចផ្ទុកផ្ទាំងទិន្នន័យរបស់អ្នកបាន។',
  'Complete your account to view activity.':
      'បំពេញគណនីរបស់អ្នកដើម្បីមើលសកម្មភាព។',
  'Profile visibility': 'ភាពមើលឃើញប្រវត្តិរូប',
  'Likes given': 'ការចូលចិត្តដែលបានផ្តល់',
  'Likes received': 'ការចូលចិត្តដែលបានទទួល',
  'Saved profiles': 'ប្រវត្តិរូបដែលបានរក្សាទុក',
  'Match rate': 'អត្រាផ្គូផ្គង',
  'Weekly activity': 'សកម្មភាពប្រចាំសប្តាហ៍',
  'Day': 'ថ្ងៃ',
  'Recent matches': 'ការផ្គូផ្គងថ្មីៗ',
  'No matches yet.': 'មិនទាន់មានការផ្គូផ្គងទេ។',
  'View matches': 'មើលការផ្គូផ្គង',
  'Generating a draft…': 'កំពុងបង្កើតសេចក្តីព្រាង…',
  'Generating interview questions…': 'កំពុងបង្កើតសំណួរសម្ភាសន៍…',
  'Help and resources': 'ជំនួយ និងធនធាន',
  'Guides, safety, terms and privacy':
      'មគ្គុទ្ទេសក៍ សុវត្ថិភាព លក្ខខណ្ឌ និងឯកជនភាព',
  'Privacy Policy': 'គោលការណ៍ឯកជនភាព',
  'Terms of Service': 'លក្ខខណ្ឌនៃការប្រើប្រាស់',
  'Contact us': 'ទាក់ទងយើង',
  'Email support': 'ជំនួយតាមអ៊ីមែល',
  'Sign in to apply': 'ចូលគណនីដើម្បីដាក់ពាក្យ',
  'Search filters': 'តម្រងស្វែងរក',
  'Experience level': 'កម្រិតបទពិសោធន៍',
  'Skills (comma separated)': 'ជំនាញ (បំបែកដោយសញ្ញាក្បៀស)',
  'Work mode': 'របៀបធ្វើការ',
  'Minimum company size': 'ទំហំក្រុមហ៊ុនអប្បបរមា',
  'Maximum company size': 'ទំហំក្រុមហ៊ុនអតិបរមា',
  'Minimum salary': 'ប្រាក់ខែអប្បបរមា',
  'Maximum salary': 'ប្រាក់ខែអតិបរមា',
  'Posted from': 'បានផ្សាយចាប់ពី',
  'Posted to': 'បានផ្សាយដល់',
  'Sort by': 'តម្រៀបតាម',
  'Apply filters': 'អនុវត្តតម្រង',
  'Reset filters': 'កំណត់តម្រងឡើងវិញ',
  'Enter a valid non-negative number.': 'បញ្ចូលលេខត្រឹមត្រូវដែលមិនអវិជ្ជមាន។',
  'Minimum cannot exceed maximum.': 'តម្លៃអប្បបរមាមិនអាចលើសអតិបរមា។',
  'Start date cannot follow end date.': 'ថ្ងៃចាប់ផ្តើមមិនអាចនៅក្រោយថ្ងៃបញ្ចប់។',
  'Best match': 'ការផ្គូផ្គងល្អបំផុត',
  'Newest first': 'ថ្មីបំផុតមុន',
  'Oldest first': 'ចាស់បំផុតមុន',
  'Company size: high to low': 'ទំហំក្រុមហ៊ុន៖ ធំទៅតូច',
  'Company size: low to high': 'ទំហំក្រុមហ៊ុន៖ តូចទៅធំ',
  'Experience: high to low': 'បទពិសោធន៍៖ ច្រើនទៅតិច',
  'Experience: low to high': 'បទពិសោធន៍៖ តិចទៅច្រើន',
  'No Experience': 'គ្មានបទពិសោធន៍',
  'Less than 1 year': 'តិចជាង ១ ឆ្នាំ',
  '1 - 2 years': '១ - ២ ឆ្នាំ',
  '3 - 5 years': '៣ - ៥ ឆ្នាំ',
  '6 - 10 years': '៦ - ១០ ឆ្នាំ',
  '10+ years': '១០+ ឆ្នាំ',
  'Under Graduate': 'ថ្នាក់បរិញ្ញាបត្រកំពុងសិក្សា',
  'Bachelor': 'បរិញ្ញាបត្រ',
  'Master': 'អនុបណ្ឌិត',
  'PhD': 'បណ្ឌិត',
  'On site': 'នៅការិយាល័យ',
  'Flexible': 'អាចបត់បែនបាន',
  'Saved search': 'ការស្វែងរកដែលបានរក្សាទុក',
  'Our community': 'សហគមន៍របស់យើង',
  'Members': 'សមាជិក',
  'Talent': 'អ្នកមានសមត្ថភាព',
  'Mon': 'ចន្ទ',
  'Tue': 'អង្គារ',
  'Wed': 'ពុធ',
  'Thu': 'ព្រហស្បតិ៍',
  'Fri': 'សុក្រ',
  'Sat': 'សៅរ៍',
  'Sun': 'អាទិត្យ',
};
